name: tinymill
favicon: null
layout_spectrum: 0.9334258472081274
typography_spectrum: 0.42468938510864973
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.4857312620151788
  lightness: 0.6392880459316075
  saturation: 0.7395579279400408
  rhythmicContrast: 0.9338992082048208
purpose: []
